Repository czfadmin/bookmarks, pull requests merged in 2024-03, with the labels that each got.

#21 feat: 增加动态改变颜色名字功能
  l10n/bundle.l10n.json
  l10n/bundle.l10n.zh.json
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands/code.ts
  src/constants/command.ts
  src/controllers/BookmarksController.ts
  src/controllers/IController.ts
  src/controllers/UniversalBookmarkController.ts
  src/providers/BaseTreeProvider.ts
  src/providers/BookmarksTreeProvider.ts
  src/providers/UniversalTreeProvider.ts
  src/utils/bookmark.ts
Labels: enhancement

#24 修复修改颜色名称,没有图标的问题
  src/bootstrap.ts
  src/services/DecorationService.ts
  src/services/ServiceManager.ts
  src/services/WorkspaceService.ts
Labels: enhancement

#26 feat:修复已知BUG, 增加`alwaysIgnore`以及`autoSwitchSingleToMultiWhenLineWrapping`两个配置项
  .github/pull-request-template.md
  .gitignore
  .vscode/bookmark-manager.json
  CHANGELOG.md
  CONTRIBUTING.md
  l10n/bundle.l10n.json
  l10n/bundle.l10n.zh.json
  package.json
  package.nls.json
  package.nls.zh.json
  src/bootstrap.ts
  src/commands/code.ts
  src/constants/extension.ts
  src/controllers/BookmarksController.ts
  src/controllers/IController.ts
  src/controllers/UniversalBookmarkController.ts
  src/services/BookmarkService.ts
  src/services/ConfigService.ts
  src/services/DecorationService.ts
  src/services/GitService.ts
  src/services/ServiceManager.ts
  src/services/StatusbarService.ts
  src/services/WorkspaceService.ts
  src/types/common.ts
  src/types/configuration.ts
  src/utils/bookmark.ts
  src/views/BaseTreeView.ts
  src/views/BookmarksTreeView.ts
  tsconfig.json
  yarn.lock
Labels: bug, enhancement

#27 Fix workspace bug
  .vscode/bookmark-manager.json
  CHANGELOG.md
  package.json
  src/controllers/BookmarksController.ts
Labels: bug

#28 Pref: 使用 mobx + mst 重构配置以及书签相关代码
  CHANGELOG.md
  package.json
  src/bootstrap.ts
  src/commands/code.ts
  src/controllers/BookmarksController.ts
  src/controllers/IController.ts
  src/controllers/UniversalBookmarkController.ts
  src/events.ts
  src/providers/BaseTreeProvider.ts
  src/providers/BookmarksTreeItem.ts
  src/providers/BookmarksTreeProvider.ts
  src/providers/UniversalTreeProvider.ts
  src/services/ConfigService.ts
  src/services/DecorationService.ts
  src/services/GutterService.ts
  src/services/index.ts
  src/stores/bookmark.ts
  src/stores/configure.ts
  src/stores/custom.ts
  src/stores/decoration.ts
  src/stores/index.ts
  src/types/code.ts
  src/types/common.ts
  src/types/configuration.ts
  src/types/index.ts
  src/utils/bookmark.ts
  src/utils/logger.ts
  src/views/BaseTreeView.ts
  src/views/BookmarksTreeView.ts
  yarn.lock
Labels: enhancement

#31 update readme
  .all-contributorsrc
  .github/pull-request-template.md
  README.md
Labels: enhancement
